[package]
authors = ["Georg Semmler <georg.semmler@giga-infosystems.com>"]
name = "diesel-oci"
version = "0.1.0"
license = "MIT OR Apache-2.0"
description = "A oci database adapter for diesel"
readme = "README.md"
keywords = ["diesel", "oci", "oracle", "sql"]
categories = ["database"]

[workspace]
members = ["oci-sys"]

[dependencies]
byteorder = "1"
libc = "0.2"
log = "0.3"
dotenv = ">=0.8, <0.11"


[dependencies.chrono]
optional = true
version = "0.4"

[dependencies.diesel]
default-features = false
features = ["with-deprecated"]
version = "1.3"

[dependencies.oci-sys]
path = "oci-sys"

[dev-dependencies]
num = { version = "0.1", default-features = false }
num-derive = "0.1"

[features]
chrono-time = ["chrono", "diesel/chrono"]
default = ["chrono-time"]

[replace]
"diesel:1.3.2" = { git = "https://github.com/GiGainfosystems/diesel", rev = "29253d78" }
"diesel_derives:1.3.0" = { git = "https://github.com/GiGainfosystems/diesel", rev = "29253d78" }
