[package]
authors = [
    "Georg Semmler <georg.semmler@giga-infosystems.com>",
    "Paul Gabriel <paul.gabriel@giga-infosystems.com>",
    "Daniel Buse <daniel.buse@giga-infosystems.com>",
]
name = "diesel-oci"
version = "0.1.0"
license = "MIT OR Apache-2.0"
description = "A oci database adapter for diesel"
readme = "README.md"
keywords = ["diesel", "oci", "oracle", "sql"]
categories = ["database"]

[workspace]
members = ["oci-sys"]

[dependencies]
byteorder = "1"
libc = "0.2"
log = "0.3"

[dependencies.chrono-time]
optional = true
version = "0.4"
package = "chrono"

[dependencies.diesel]
default-features = false
features = ["with-deprecated", "unstable"]
version = "=1.4.3"

[dependencies.diesel-dynamic-schema]
optional = true
rev = "7bf1b32b5fe577cbf225d1b2aa4ec7d5c7f2c7c4"
git = "https://github.com/GiGainfosystems/diesel-dynamic-schema"

[dependencies.oci-sys]
path = "oci-sys"

[dev-dependencies]
dotenv = ">=0.8, <0.11"
num = { version = "0.1", default-features = false }
num-derive = "0.1"

[features]
default = ["chrono", "r2d2", "dynamic-schema"]
chrono = ["chrono-time", "diesel/chrono"]
r2d2 = ["diesel/r2d2"]
dynamic-schema = ["diesel-dynamic-schema"]
gst = []

[patch.crates-io]
diesel = {git = "https://github.com/GiGainfosystems/diesel", rev = "819ab862c2286ff08725ac3800722228a90b71e6"}
diesel_derives = {git = "https://github.com/GiGainfosystems/diesel", rev = "819ab862c2286ff08725ac3800722228a90b71e6"}
