[package]
authors = ["Georg Semmler <georg.semmler@giga-infosystems.com>"]
name = "diesel-oci"
version = "0.1.0"
license = "MIT OR Apache-2.0"
description = "A oci database adapter for diesel"
readme = "README.md"
keywords = ["diesel", "oci", "oracle", "sql"]
categories = ["database"]

[workspace]
members = ["oci-sys"]

[dependencies]
byteorder = "1"
libc = "0.2"
log = "0.3"
dotenv = ">=0.8, <0.11"
bigdecimal = { version = ">= 0.0.10, < 0.0.12"}


[dependencies.chrono]
optional = true
version = "0.4"

[dependencies.diesel]
default-features = false
version = "1.3.2"

[dependencies.oci-sys]
path = "oci-sys"

[features]
chrono-time = ["chrono", "diesel/chrono"]
default = ["chrono-time"]
